sudo: false

jobs:
  include:
    - stage: wild-monitor-build-and-deploy
      language: java
      jdk: openjdk8
      env:
        - NODE_VERSION="11.9.0"
      before_install:
        - nvm install $NODE_VERSION
      install:
        - npm i -g npm yarn
      before_script:
        - export PATH=$PATH:$TRAVIS_BUILD_DIR/wild-monitor-web/node_modules/.bin
        - cd $TRAVIS_BUILD_DIR/wild-monitor-web
        - yarn install
      script:
        - yarn test
        - yarn build:prod
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew clean :wild-monitor-service:build --no-daemon
      deploy:
        provider: cloudfoundry
        api: https://api.run.pcfone.io
        organization: pivot-ddubson
        space: development
        manifest: "."
        on:
          branch: master
        username:
          secure: "UxHQjtv1VlN3odO9nzsh/ydnHd+jH8gFZ3dM6OuTRiTshicgQPGbIXmiy/o89geI/neLh175hMlROub5aHfQJdirJI2BPqcAWft1GUP2WV9QrhzeaLqBHTnRCLCR9ttFAGAacFLO6puuJhe9oUscb2dQSoBA3fqwK2DtD+klV/Bjs5UHe519akKpnzFBKC/U+H/EnIpUDZdZetZ7owyi3cYEzsX97+ff8t9ILnsoXpB/gAtCaE3G6HO1n9hrwPWgQT3udlPY6ySWGUeb0h5DYKQ64WBe6PkNOVTHC5MUdMCoiuww0/5kCx0kFafwdCDZaRZpWtuElBH2nChRAbrfAWTVxDSkaRqE2U5vqFRRk3jfy9DdLEkkt7YfZnaSMUtpIx7vG2Ihwh/DmNL3C+jXgM8QU9f9it9Y86rVc54bawFhD3C4KhmSU+Ej3cUi79oCpVL3V9MRn6tZK/nSM0c0+FCr5i1NoF6y/mFgZECWMX6lYP+DGwnYqGkYUHEuJF0RSFeeLvzDCJ/MExoFr/M+36k3ysHHz26Mn/KCD8n0dvaicHjmNi+riQOxQGzX31Ccp+wsSlTfDjntrObLrDJP2ZiU4b9UPhgkVPfLGyWJct94zHgp7DDtn3zeDWgQCRCDbiOMP9kqd/F8TaaibllWT9ccbfwqyCxKyNuKnfksatw="
        password:
          secure: "BbtzF0Len+mSU0GBsUHRBw3cO7FDuHf06Wi60oi2aSjc10qHvCO5H7uEdQkX2QZQAeaBNHvyHsei/K4dT2m6sNt5iFIw3tCvPTspTorhEXK+7tU3AhjgVejKkMaOFN39Z51Cux1T3vRidLr/yC5f2ml1U9RKmSyWcQNHgE/jqxRy214SgShbxy0m+0OySPRfaVtwQu92049Am70+LWYXU43mCdgL1ASSGI3V1PfDtJoAbsbS64hKw3BGml08AYBBx0Ou55sM5t0Z1PtMX7pY/Zp3tiqBSD0gZOFZsqJiOELUa5HcvXmLVHKv0rLBHYNmIiYWKXf/E8SKuSece7T+GuAAOFWLvbqApX220jyfGBYDOylaRJ8ng0IXgw2lrgLEYXJxZqb6/4BPLYK9OCT3P7XLk7RhOEYnz5uqLWrNs7nh5/T3j7wBecUwkv0btENp/udz27wowX6kWua0AZQWzyZxazx8WkEaCItnULzT2baGtMa7K6WRlucDKr3B3SJdrp4JOmlcodNvsNdrK2l1R5dY8a4QXhj7wg7NgmTEmgU8pLLpNrcbmmFoX17ySK+bKKS4QFSy8mCjhn8we8cuyB3SHJZtBQF0eQNj/IcNMtXBRXFRkKv84+a59jOhmCQqzJUOKKzOMt7Ns20QB3wCyQTUuf3sanNQIqdZmROy4Io="