sudo: false
language: java
jdk: openjdk8
install:
  - npm i -g yarn
cache:
  yarn: true
  directories:
    - wild-monitor-web/node_modules
    - ~/wild-monitor-web/.cache
jobs:
  include:
    - stage: wild-monitor-web-build
      script:
        - yarn build
    - stage: test
      script:
        - ./gradlew --no-daemon --info test
stages:
  - name: test
  - name: wild-monitor-web-build