sudo: false
language: java
jdk: openjdk8
install:
  - echo "skip default gradlew assemble"
jobs:
  include:
    - stage: test
      script:
        - ./gradlew --no-daemon --info test
stages:
  - name: test